### ISSUE TITLE
Podcasts - Liste mit ToDos

### ISSUE THREAD

**Issue by boydroid** [hacken-in/website#230]
- [ ] iTunes Button [Issue 223](https://github.com/nerdhub/hcking/issues/223)
- [x] mp3 Download im Podcast [Issue 218](https://github.com/nerdhub/hcking/issues/218)
- [x] Text-Änderungen in Podcast Feeds [Issue 228](https://github.com/nerdhub/hcking/issues/228)
- [x] Neue Richtlinien von iTunes umsetzen [Issue 229](https://github.com/nerdhub/hcking/issues/229)
- [ ] Podcast Player bricht ständig ab [Issue 231](https://github.com/nerdhub/hcking/issues/231)
