### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by moonglum** [hacken-in/website#262]
- [x] Wir wollen anders aussehen
- [x] Styleguide bzw. Living Styleguide wie zB. [Flat UI](http://designmodo.github.io/Flat-UI/)
- [x] Mobile First: Wir wollen toll aussehen auf mobilen Endgeräten. Vielleicht Hamburger/Schublade für alles außer Events.
- [x] Github/Flattr/Twitter Links sollen prominent auf der Seite gezeigt werden
- [x] Tags eines Events darstellen (evtl. nur via Mouseover)
- [x] Schöne Vorschlagsseite
- [x] Tagesauswahl die Bodo-sicher ist
- [x] Neues Logo (für die Seite, Favicon, Twitter & ADN)
- [ ] ~~Wir wollen Badges für Core Team, Kontributoren, Organisatoren, Kuratoren~~ #459
- [ ] ~~Wir wollen auch Badges für Events "Hat CoC"~~ #458
- [ ] ~~Tags lieben / hassen ähnlich wie jetzt~~ #460
- [ ] ~~Events mit geliebten Tags sollen hervorgehoben werden~~ #460
- [x] Dropdown für Städteauswahl
- [ ] Seitendesigns
  - [x] Startseite / Kalender
  - [x] SingleEvent Seite
  - [x] Benutzerseite
  - [x] Suchergebnisse
  - [x] Vorschlagen
  - [x] Humans / Team: Mehrere Segmente wie Team, Organistatoren...
  - [x] About Page: Manifest, Wie kann ich mitmachen, Wie kann ich Organisator werden...
  - [x] Impressum
  - [ ] ~~Venue Seite~~ #457
  - [ ] ~~Kalender Export~~ #461
