### ISSUE TITLE
Additional meta information about events

### ISSUE THREAD

**Issue by moonglum** [hacken-in/website#458]
- [ ] Does the event have a CoC? If so, add a badge for it.
- [ ] Does it require registering? If so, add a badge for it and a link to registering.
- [ ] Does the event have an entrance fee? If so, add a badge and an amount.
