### ISSUE TITLE
Les Revenants

### ISSUE THREAD

**Issue by moonglum** [hacken-in/website#621]
@moonglum and @bascht did some stuff (#616 and on the master branch). They comitted sins. And some stuff was forgotten. Those tasks returned to be done:
- [x] Setup Postgres Backup
- [x] Make the recurring tasks work
- [x] Regularly copy the production database and assets to staging (#623)
- [x] config/initializers/recaptcha.rb Token has to be an environment variable (#633)
- [x] Do correctly: Service Symlinks, htaccess symlinks, public symlinks (#635)
- [x] Add uberspace Banner (#625)
- [x] Remove last occurrences of shelly `CLOUD_NAME` (#634)
- [x] Check proper Restart of Service after Travis Deployment

**Comment by bascht** [comment]
:white_check_mark:  Postgres backup is done by @uberspace at 05:00am every day.

**Comment by moonglum** [comment]
About "Regularly copy the production database and assets to staging":

I think the best solution would be to do that before every master.hacken.in deployment. That means that we always know that new migrations etc. work with our current dataset.

**Comment by moonglum** [comment]
We will try to replace our whenever setup with [runwhen](https://wiki.uberspace.de/system:runwhen)

**Comment by moonglum** [comment]
Maybe we can get around possible port conflicts and information duplication about the port number by using unix sockets?

**Comment by moonglum** [comment]
We could also use ![hosted on asteroids](https://uberspace.de/static/badges/badge-white-57430c03a636490df773b4d15bd2fdb962763110.png) in the sidebar :smile: 
<img width="230" alt="screen shot 2016-03-26 at 00 35 38" src="https://cloud.githubusercontent.com/assets/95788/14056317/b0712f8a-f2ea-11e5-975a-ca3cd9d1eba2.png">

**Comment by bascht** [comment]
That looks waaaaaaaaaaaay nicer :3

**Comment by moonglum** [comment]
All done.
